### ISSUE TITLE
Installing has stuck on 44%

### ISSUE THREAD

**Issue by amirmallaei** [ROBOTIS-GIT/turtlebot3_autorace_2020#13]
I am trying to install the package on turtlebot 3 as explained in the website. but the installation has stuck at 44%.

[ 34%] Built target turtlebot3_autorace_msgs_generate_messages_py
[ 36%] Built target turtlebot3_autorace_msgs_generate_messages_cpp
[ 39%] Built target turtlebot3_autorace_msgs_generate_messages_eus
[ 40%] Built target turtlebot3_autorace_msgs_generate_messages_lisp
[ 42%] Building CXX object image_common/camera_calibration_parsers/CMakeFiles/camera_calibration_parsers.dir/src/parse.cpp.o
[ 43%] Building CXX object image_common/camera_calibration_parsers/CMakeFiles/camera_calibration_parsers.dir/src/parse_ini.cpp.o
[ 44%] Building CXX object image_common/image_transport/CMakeFiles/image_transport.dir/src/camera_common.cpp.o

**Comment by ROBOTIS-Ashe** [comment]
Hi @amirmallaei. 
Thank you for your questions.
opencv takes a lot of time to build.
Please continue to wait for the build to complete.

Thank you.

**Comment by ROBOTIS-Ashe** [comment]
This issue will be closed since there were no actions for a while. 
You can reopen this issue to show this issue to the users whenever. 

Thanks.
