### ISSUE TITLE
How to complete all missions at once processes？

### ISSUE THREAD

**Issue by EndlessLoops** [ROBOTIS-GIT/turtlebot3_autorace_2020#14]
I want to  complete all missions at once processes like first kinetic version of turtlebot3_autorace.Do you have an existing example or tutorial?

**Comment by ROBOTIS-Ashe** [comment]
Hello. @EndlessLoops . Thanks for the question.
Unfortunately, turtlebot3_autorace_2020 is provided only for performing each mission.
We do not support complete all missions at once processes.
Thank you for your understanding.

**Comment by EndlessLoops** [comment]
Okay,thanks for your quick reply.
