### ISSUE TITLE
Unable to find camera's settings

### ISSUE THREAD

**Issue by fabiocyro** [ROBOTIS-GIT/turtlebot3_autorace_2020#15]
Hello,

Hope everyone is doing well =)

I used autorace 2019 on ROS melodic and one of the key points to make everything work was changing the camera's settings such as contrast, ISO, shutter speed, saturation etc. 

I was able to do that because it seems that it used raspicam node instead of cv_camera and there was an extra folder called camera_calibration amongst extrinsinc and intrinsinc calibration folders also where you just had to change the values there. 

Unfortunately, I'm not finding a similar folder for autorace 2020 using noetic. And trying to work with raspicam doesn't seem to work either (well, I can use it normally for image acquisition, but not with autorace 2020).

Did I do something wrong or was it supposed to be like this?

Thanks a lot in advance!

**Comment by ROBOTIS-Ashe** [comment]
Hello @fabiocyro . thanks for the question

Autorace 2020 supports Noetic.
Unfortunately, raspicam does not support the noetic version, so we replaced it with cv_camera.
Settings such as contrast, ISO, shutter speed, and saturation are functions supported by raspicam, so cv_camera does not support those functions.

I am attaching the link below. You can check out more information.
e-manual : [Autorace2020](https://emanual.robotis.com/docs/en/platform/turtlebot3/autonomous_driving/#autonomous-driving)

thank you.

**Comment by fabiocyro** [comment]
Hello @ashekim, thank you for your answer!

Oh ok, well at least I'm relieved now that I know that I didn't do anything wrong haha.

I was doing some research after I posted this and at least I can change some of the parameters directly on the driver, so I guess I will have to go through this approach!

Thank you for the help!
